[phases.setup]
nixPkgs = ["nodejs", "google-chrome", "cacert"]

[phases.install]
cmds = ["npm install"]

[variables]
CHROME_PATH = "/usr/bin/google-chrome-stable"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
